import { ColorTokens, ThemeId } from './tokens';

// Each theme is a complete, self-contained palette -- inspired by (not a
// clone of) a specific, real, well-regarded source, chosen for genuine
// distinctiveness rather than a shared neutral shell with a different
// accent dropped in:
//   light  -- Flexoki (github.com/kepano/flexoki), a warm-paper palette
//             designed specifically for reading/writing apps.
//   dark   -- Tokyo Night, a cool blue-purple dark scheme.
//   sepia  -- a warm reading-mode palette (Kindle/Instapaper-style sepia),
//             custom-built in the same spirit, terracotta accent.
// Semantic colors (warning/success/notification/variable) are tuned per
// theme rather than shared, so each one reads as a coherent, deliberate
// whole instead of three neutrals wearing the same borrowed accents.
export const THEMES: Record<ThemeId, ColorTokens> = {
  light: {
    '--background-color': '#fffcf0',
    '--text-color': '#100f0f',
    '--border-color': '#ddd9ca',
    '--focus-border-color': '#205ea6',
    '--text-primary-color': '#100f0f',
    '--text-warning-color': '#af3029',
    '--icon-color': '#6f6e69',
    '--icon-color-highlight': '#66800b',
    '--primary-color': '#205ea6',
    '--primary-color-hover': '#17517d',
    '--primary-text-color': '#fffcf0',
    '--notification-color': '#ad8301',
    '--graph-background': '#fffcf0',
    '--component-border-color': '#ddd9ca',
    '--divider-color': '#ddd9ca',
    '--node-bg': '#ffffff',
    '--node-border': '#ddd9ca',
    '--node-text-color': '#100f0f',
    '--node-secondary-text-color': '#6f6e69',
    '--node-handle-bg': '#9f9d96',
    '--node-schema-bg': '#f2eee0',
    '--node-schema-text-color': '#100f0f',
    '--node-order-bg': '#205ea6',
    '--node-order-text-color': '#fffcf0',
    '--node-column-bg': '#f2eee0',
    '--node-column-border': '#e6e2d3',
    '--node-column-text-color': '#100f0f',
    '--node-candidate-column-border': '#ad8301',
    '--node-candidate-column-text-color': '#6f6e69',
    '--node-candidate-container-bg': 'transparent',
    '--node-candidate-container-border': '#ddd9ca',
    '--node-operation-label-color': '#6f6e69',
    '--node-suggested-bg': '#ffffff',
    '--node-suggested-border': '#ddd9ca',
    '--node-candidate-bg': '#e4edf7',
    '--node-candidate-border': '#205ea6',
    '--node-candidate-text-color': '#100f0f',
    '--node-variable-border': '#a02f6f',
    '--node-variable-bg': 'rgba(160, 47, 111, 0.08)',
    '--node-variable-label-color': '#a02f6f',
    '--canvas-bg': '#fffcf0',
    '--canvas-grid-dot': '#e6e2d3',
    '--canvas-node-bg': '#ffffff',
    '--canvas-node-bg-current': '#e4edf7',
    '--canvas-node-border': '#ddd9ca',
    '--canvas-node-border-current': '#205ea6',
    '--canvas-trace': '#205ea6',
    '--canvas-trace-uncertain': '#9f9d96',
    '--canvas-trace-unresolved': '#ad8301',
    '--canvas-warn': '#af3029',
    '--canvas-pin': '#9f9d96',
    '--canvas-text': '#100f0f',
    '--canvas-text-dim': '#6f6e69',
    '--canvas-accent-text': '#fffcf0',
    '--canvas-chip-bg': '#f2eee0',
    '--canvas-chip-border': '#e6e2d3',
    '--canvas-picker-bg': '#ffffff',
    '--canvas-picker-border': '#ddd9ca',
    '--canvas-container-border': '#a02f6f',
    '--canvas-container-bg': 'rgba(160, 47, 111, 0.08)',
    '--canvas-container-label': '#a02f6f',
  },

  dark: {
    '--background-color': '#1a1b26',
    '--text-color': '#c0caf5',
    '--border-color': '#363b58',
    '--focus-border-color': '#7aa2f7',
    '--text-primary-color': '#c0caf5',
    '--text-warning-color': '#f7768e',
    '--icon-color': '#787c99',
    '--icon-color-highlight': '#9ece6a',
    '--primary-color': '#7aa2f7',
    '--primary-color-hover': '#7aa2f7',
    '--primary-text-color': '#1a1b26',
    '--notification-color': '#e0af68',
    '--graph-background': '#1a1b26',
    '--component-border-color': '#363b58',
    '--divider-color': '#363b58',
    '--node-bg': '#1f2335',
    '--node-border': '#363b58',
    '--node-text-color': '#c0caf5',
    '--node-secondary-text-color': '#787c99',
    '--node-handle-bg': '#565f89',
    '--node-schema-bg': '#24283b',
    '--node-schema-text-color': '#c0caf5',
    '--node-order-bg': '#7aa2f7',
    '--node-order-text-color': '#1a1b26',
    '--node-column-bg': '#24283b',
    '--node-column-border': '#363b58',
    '--node-column-text-color': '#c0caf5',
    '--node-candidate-column-border': '#e0af68',
    '--node-candidate-column-text-color': '#787c99',
    '--node-candidate-container-bg': 'transparent',
    '--node-candidate-container-border': '#363b58',
    '--node-operation-label-color': '#787c99',
    '--node-suggested-bg': '#1f2335',
    '--node-suggested-border': '#363b58',
    '--node-candidate-bg': '#283457',
    '--node-candidate-border': '#7aa2f7',
    '--node-candidate-text-color': '#c0caf5',
    '--node-variable-border': '#bb9af7',
    '--node-variable-bg': 'rgba(187, 154, 247, 0.12)',
    '--node-variable-label-color': '#d4bfff',
    '--canvas-bg': '#1a1b26',
    '--canvas-grid-dot': '#242837',
    '--canvas-node-bg': '#1f2335',
    '--canvas-node-bg-current': '#283457',
    '--canvas-node-border': '#363b58',
    '--canvas-node-border-current': '#7aa2f7',
    '--canvas-trace': '#7aa2f7',
    '--canvas-trace-uncertain': '#565f89',
    '--canvas-trace-unresolved': '#e0af68',
    '--canvas-warn': '#f7768e',
    '--canvas-pin': '#565f89',
    '--canvas-text': '#c0caf5',
    '--canvas-text-dim': '#787c99',
    '--canvas-accent-text': '#1a1b26',
    '--canvas-chip-bg': '#24283b',
    '--canvas-chip-border': '#363b58',
    '--canvas-picker-bg': '#1f2335',
    '--canvas-picker-border': '#363b58',
    '--canvas-container-border': '#bb9af7',
    '--canvas-container-bg': 'rgba(187, 154, 247, 0.12)',
    '--canvas-container-label': '#d4bfff',
  },

  sepia: {
    '--background-color': '#f4ecd8',
    '--text-color': '#4a3b2a',
    '--border-color': '#e3d5b0',
    '--focus-border-color': '#bf6e4e',
    '--text-primary-color': '#4a3b2a',
    '--text-warning-color': '#b54a3f',
    '--icon-color': '#8a7a63',
    '--icon-color-highlight': '#6e8b3d',
    '--primary-color': '#bf6e4e',
    '--primary-color-hover': '#a85a3d',
    '--primary-text-color': '#fbf6ea',
    '--notification-color': '#b0791c',
    '--graph-background': '#f4ecd8',
    '--component-border-color': '#e3d5b0',
    '--divider-color': '#e3d5b0',
    '--node-bg': '#fbf6ea',
    '--node-border': '#e3d5b0',
    '--node-text-color': '#4a3b2a',
    '--node-secondary-text-color': '#8a7a63',
    '--node-handle-bg': '#a8977a',
    '--node-schema-bg': '#ece0c4',
    '--node-schema-text-color': '#4a3b2a',
    '--node-order-bg': '#bf6e4e',
    '--node-order-text-color': '#fbf6ea',
    '--node-column-bg': '#ece0c4',
    '--node-column-border': '#e0d0ac',
    '--node-column-text-color': '#4a3b2a',
    '--node-candidate-column-border': '#b0791c',
    '--node-candidate-column-text-color': '#8a7a63',
    '--node-candidate-container-bg': 'transparent',
    '--node-candidate-container-border': '#e3d5b0',
    '--node-operation-label-color': '#8a7a63',
    '--node-suggested-bg': '#fbf6ea',
    '--node-suggested-border': '#e3d5b0',
    '--node-candidate-bg': '#efe2c2',
    '--node-candidate-border': '#bf6e4e',
    '--node-candidate-text-color': '#4a3b2a',
    '--node-variable-border': '#8c5a82',
    '--node-variable-bg': 'rgba(140, 90, 130, 0.10)',
    '--node-variable-label-color': '#714469',
    '--canvas-bg': '#f4ecd8',
    '--canvas-grid-dot': '#e7d9b4',
    '--canvas-node-bg': '#fbf6ea',
    '--canvas-node-bg-current': '#efe2c2',
    '--canvas-node-border': '#e3d5b0',
    '--canvas-node-border-current': '#bf6e4e',
    '--canvas-trace': '#bf6e4e',
    '--canvas-trace-uncertain': '#a8977a',
    '--canvas-trace-unresolved': '#b0791c',
    '--canvas-warn': '#b54a3f',
    '--canvas-pin': '#a8977a',
    '--canvas-text': '#4a3b2a',
    '--canvas-text-dim': '#8a7a63',
    '--canvas-accent-text': '#fbf6ea',
    '--canvas-chip-bg': '#ece0c4',
    '--canvas-chip-border': '#e0d0ac',
    '--canvas-picker-bg': '#fbf6ea',
    '--canvas-picker-border': '#e3d5b0',
    '--canvas-container-border': '#8c5a82',
    '--canvas-container-bg': 'rgba(140, 90, 130, 0.10)',
    '--canvas-container-label': '#714469',
  },
};

// Whether TableNode's signature bottom-left notch (the "IC package pin-1"
// cut, see components/canvas/nodes/TableNode.tsx) fits a theme's character.
// It reads as a technical/schematic detail, which suits Dark's blueprint-
// adjacent coolness; Light and Sepia are meant to feel softer and more
// paper-like, so they get a plain rounded card instead. This is the one
// piece of node *shape* (not just color) that changes with the theme.
export const NOTCHED_NODE_THEMES: ThemeId[] = ['dark'];
