export const lightColors = {
  '--background-color': '#ffffff',
  '--text-color': '#333333',
  '--border-color': '#d3d3d3',
  '--focus-border-color': 'rgb(25, 118, 210)',
  '--text-primary-color': '#333333',
  '--text-warning-color': '#333333',
  '--icon-color': '#9e9e9e',
  '--icon-color-highlight': '#4caf50',
  '--primary-color': '#1976d2',
  '--primary-color-hover': '#1565c0',
  '--primary-text-color': '#ffffff',
  '--notification-color': '#e08e3d',
  '--graph-background': '#ffffff',
  '--component-border-color': '#d3d3d3',
  '--divider-color': '#808080',
  '--node-bg': '#d3d3d3',
  '--node-border': '#000000',
  '--node-text-color': '#000000',
  '--node-secondary-text-color': '#000000',
  '--node-handle-bg': '#a9a9a9',
  '--node-schema-bg': '#ffffff',
  '--node-schema-text-color': '#000000',
  '--node-order-bg': '#800000',
  '--node-order-text-color': '#ffffff',
  '--node-column-bg': '#f0f0f0',
  '--node-column-border': '#dddddd',
  '--node-column-text-color': '#000000',
  '--node-candidate-column-border': '#f39c12',
  '--node-candidate-column-text-color': '#666666',
  '--node-candidate-container-bg': 'transparent',
  '--node-candidate-container-border': '#eeeeee',
  '--node-operation-label-color': '#666666',
  '--node-suggested-bg': '#ffffff',
  '--node-suggested-border': '#ffa500',
  '--node-candidate-bg': '#FFD700',
  '--node-candidate-border': '#ffa500',
  '--node-candidate-text-color': '#000000',

  // Canvas mode's own palette ("schematic/blueprint" - see the plan doc's
  // follow-up pass 7) - a separate namespace rather than reusing --node-*,
  // which SelectedNodeComponent/RelationHandles/the classic graph etc. also
  // read; redefining those here would restyle the classic graph too.
  '--canvas-bg': '#eef4fa',
  '--canvas-grid-dot': '#c8dced',
  '--canvas-node-bg': '#ffffff',
  '--canvas-node-bg-current': '#dbeeff',
  '--canvas-node-border': '#9fc0dc',
  '--canvas-node-border-current': '#1c6fa8',
  '--canvas-trace': '#1c6fa8',
  '--canvas-trace-uncertain': '#6a93ad',
  '--canvas-trace-unresolved': '#c97a12',
  '--canvas-warn': '#c1484c',
  '--canvas-pin': '#5c86a8',
  '--canvas-text': '#0f2337',
  '--canvas-text-dim': '#4d6d85',
  '--canvas-accent-text': '#ffffff',
  '--canvas-chip-bg': '#e3edf6',
  '--canvas-chip-border': '#b7d0e4',
  '--canvas-picker-bg': '#ffffff',
  '--canvas-picker-border': '#9fc0dc',
};

export const darkColors = {
  '--background-color': '#21252b',
  '--text-color': '#abb2bf',
  '--border-color': '#4b5263',
  '--focus-border-color': '#61afef',
  '--text-primary-color': '#abb2bf',
  '--text-warning-color': '#e06c75',
  '--icon-color': '#5c6370',
  '--icon-color-highlight': '#98c379',
  '--primary-color': '#61afef',
  '--primary-color-hover': '#528bff',
  '--primary-text-color': '#282c34',
  '--notification-color': '#e08e3d',
  '--graph-background': '#21252b',
  '--component-border-color': '#4b5263',
  '--divider-color': '#5c6370',
  '--node-bg': '#4b5263',
  '--node-border': '#61afef',
  '--node-text-color': '#d7dce2',
  '--node-secondary-text-color': '#9ca3af',
  '--node-handle-bg': '#5c6370',
  '--node-schema-bg': '#282c34',
  '--node-schema-text-color': '#d7dce2',
  '--node-order-bg': '#e06c75',
  '--node-order-text-color': '#282c34',
  '--node-column-bg': '#282c34',
  '--node-column-border': '#5c6370',
  '--node-column-text-color': '#d7dce2',
  '--node-candidate-column-border': '#f39c12',
  '--node-candidate-column-text-color': '#abb2bf',
  '--node-candidate-container-bg': 'transparent',
  '--node-candidate-container-border': '#4b5263',
  '--node-operation-label-color': '#9ca3af',
  '--node-suggested-bg': '#4b5263',
  '--node-suggested-border': '#f39c12',
  '--node-candidate-bg': '#61afef',
  '--node-candidate-border': '#61afef',
  '--node-candidate-text-color': '#1a1a1a',

  // Canvas mode's own palette ("schematic/blueprint") - see the light
  // palette's matching comment above for why this is a separate namespace.
  '--canvas-bg': '#0a1826',
  '--canvas-grid-dot': '#1c3b57',
  '--canvas-node-bg': '#0f2337',
  '--canvas-node-bg-current': '#123554',
  '--canvas-node-border': '#2c5578',
  '--canvas-node-border-current': '#4fd1ff',
  '--canvas-trace': '#4fd1ff',
  '--canvas-trace-uncertain': '#7fb8d6',
  '--canvas-trace-unresolved': '#f5a623',
  '--canvas-warn': '#e0575b',
  '--canvas-pin': '#5c86a8',
  '--canvas-text': '#dbeeff',
  '--canvas-text-dim': '#7ba3c2',
  '--canvas-accent-text': '#0a1826',
  '--canvas-chip-bg': '#132a41',
  '--canvas-chip-border': '#28577c',
  '--canvas-picker-bg': '#0f2337',
  '--canvas-picker-border': '#2c5578',
};